"use client"

import { useState, useEffect } from "react"
import { api } from "@/lib/api"
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
    DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { useToast } from "@/hooks/use-toast"
import { Wallet, Landmark, User, CreditCard, Share2, Loader2, Check } from "lucide-react"
import { cn } from "@/lib/utils"

interface Account {
    id: string
    name: string
    type: string
    lastReportSentAt: string | null
    balance: number
}

interface ShareReportModalProps {
    isOpen: boolean
    onClose: () => void
}

const ACCOUNT_TYPE_ICONS: Record<string, any> = {
    cash: Wallet,
    bank: Landmark,
    person: User,
    other: CreditCard,
}

export function ShareReportModal({ isOpen, onClose }: ShareReportModalProps) {
    const { toast } = useToast()
    const [accounts, setAccounts] = useState<Account[]>([])
    const [loading, setLoading] = useState(true)
    const [sharing, setSharing] = useState(false)
    const [selectedAccountId, setSelectedAccountId] = useState<string | null>(null)

    useEffect(() => {
        if (isOpen) {
            loadAccounts()
        }
    }, [isOpen])

    const loadAccounts = async () => {
        try {
            setLoading(true)
            const data = await api.getAccounts()
            setAccounts(data)
            // Auto-select default account if available
            const defaultAcc = data.find((a: any) => a.isDefault)
            if (defaultAcc) setSelectedAccountId(defaultAcc.id)
        } catch (error) {
            toast({
                title: "Error",
                description: "Failed to load accounts",
                variant: "destructive",
            })
        } finally {
            setLoading(false)
        }
    }

    const handleShare = async () => {
        if (!selectedAccountId) return

        setSharing(true)
        try {
            const account = accounts.find((a) => a.id === selectedAccountId)
            if (!account) return

            // Fetch all transactions for this account
            const transactions = await api.getTransactions(selectedAccountId)

            // Filter transactions after lastReportSentAt
            const lastSent = account.lastReportSentAt ? new Date(account.lastReportSentAt) : new Date(0)

            const newTransactions = transactions
                .filter((t: any) => new Date(t.date) > lastSent)
                .sort((a: any, b: any) => new Date(a.date).getTime() - new Date(b.date).getTime())

            if (newTransactions.length === 0) {
                toast({
                    title: "No new transactions",
                    description: "There are no new transactions to report since the last one.",
                })
                setSharing(false)
                return
            }

            // Calculate Opening Balance
            // Opening Balance = Current Account Balance - Total Change from new transactions
            const totalChange = newTransactions.reduce((acc: number, t: any) => {
                return t.type === "income" ? acc + t.amount : acc - t.amount
            }, 0)

            const openingBalance = account.balance - totalChange

            // Build the message
            let currentRunningBalance = openingBalance
            let message = `📊 *${account.name} Ledger Report*\n\n`
            message += `📌 *Previous Balance:* ${openingBalance.toLocaleString()} Rs\n\n`

            newTransactions.forEach((t: any) => {
                const amountStr = t.type === "income" ? `+${t.amount}` : `-${t.amount}`
                currentRunningBalance = t.type === "income" ? currentRunningBalance + t.amount : currentRunningBalance - t.amount

                const label = t.description || t.categoryId?.name || "Other"
                message += `🔹 ${label} (${amountStr}) = ${currentRunningBalance.toLocaleString()} Rs\n`
            })

            message += `\n✅ *Current Balance: ${currentRunningBalance.toLocaleString()} Rs*\n\n`
            message += `_Generated by DevinBook_`

            // Share via WhatsApp
            const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`
            window.open(whatsappUrl, "_blank")

            // Mark as sent
            await api.markReportSent(selectedAccountId)

            toast({
                title: "Report Shared",
                description: "Account state updated successfully.",
            })

            onClose()
        } catch (error) {
            toast({
                title: "Sharing Failed",
                description: "Failed to generate or mark report.",
                variant: "destructive",
            })
        } finally {
            setSharing(false)
        }
    }

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="w-[92vw] sm:max-w-[400px] rounded-[32px] p-0 overflow-hidden border-none shadow-2xl bg-white dark:bg-slate-950 mx-auto">
                <DialogHeader className="p-8 pb-4">
                    <DialogTitle className="text-2xl font-black text-slate-900 dark:text-white">Share Report</DialogTitle>
                    <DialogDescription className="text-sm font-medium text-slate-500 dark:text-slate-400">
                        Select an account to share its recent transactions.
                    </DialogDescription>
                </DialogHeader>

                <div className="px-8 py-2">
                    <ScrollArea className="h-[300px] pr-4">
                        <div className="space-y-3">
                            {loading ? (
                                <div className="flex flex-col items-center justify-center h-[200px] space-y-4">
                                    <Loader2 className="h-8 w-8 animate-spin text-primary opacity-20" />
                                    <p className="text-xs font-bold text-muted-foreground uppercase tracking-widest">Loading Accounts...</p>
                                </div>
                            ) : (
                                accounts.map((account) => {
                                    const Icon = ACCOUNT_TYPE_ICONS[account.type] || ACCOUNT_TYPE_ICONS.other
                                    const isSelected = selectedAccountId === account.id

                                    return (
                                        <button
                                            key={account.id}
                                            onClick={() => setSelectedAccountId(account.id)}
                                            className={cn(
                                                "w-full p-5 rounded-[24px] flex items-center justify-between transition-all border-2 text-left",
                                                isSelected
                                                    ? "bg-primary/10 border-primary shadow-lg shadow-primary/5"
                                                    : "bg-slate-100 dark:bg-slate-900 border-transparent hover:bg-slate-200 dark:hover:bg-slate-800"
                                            )}
                                        >
                                            <div className="flex items-center gap-4">
                                                <div className={cn(
                                                    "w-12 h-12 rounded-2xl flex items-center justify-center transition-colors shadow-sm",
                                                    isSelected ? "bg-primary text-primary-foreground" : "bg-white dark:bg-slate-800 text-slate-400 dark:text-slate-500"
                                                )}>
                                                    <Icon className="h-6 w-6" />
                                                </div>
                                                <div>
                                                    <p className={cn("font-black text-sm", isSelected ? "text-primary dark:text-white" : "text-slate-700 dark:text-slate-300")}>{account.name}</p>
                                                    <p className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mt-0.5">
                                                        Rs {account.balance.toLocaleString()}
                                                    </p>
                                                </div>
                                            </div>
                                            {isSelected && (
                                                <div className="w-6 h-6 rounded-full bg-primary flex items-center justify-center text-white shadow-lg shadow-primary/20">
                                                    <Check className="h-4 w-4" />
                                                </div>
                                            )}
                                        </button>
                                    )
                                })
                            )}
                        </div>
                    </ScrollArea>
                </div>

                <DialogFooter className="p-8 pt-4 bg-slate-50/50 dark:bg-white/[0.02] flex flex-row gap-4">
                    <Button
                        variant="ghost"
                        onClick={onClose}
                        className="h-14 rounded-2xl font-black text-xs tracking-widest uppercase flex-1 text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"
                    >
                        Cancel
                    </Button>
                    <Button
                        disabled={!selectedAccountId || sharing || loading}
                        onClick={handleShare}
                        className="h-14 rounded-2xl font-black text-xs tracking-widest uppercase flex-1 bg-primary text-primary-foreground hover:bg-primary/90 shadow-xl shadow-primary/20 dark:shadow-primary/10 border-none"
                    >
                        {sharing ? (
                            <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                            <div className="flex items-center justify-center gap-2">
                                <Share2 className="h-4 w-4" />
                                <span>Share</span>
                            </div>
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    )
}
